modLoader="javafml" #mandatory

loaderVersion="[40,)"

license="All Rights Reserved"

# issueTrackerURL="http://my.issue.tracker/"

[[mods]]

modId="swlm"

version="${file.jarVersion}"

displayName="Star Worm Lighting Mod"

# updateJSONURL="http://myurl.me/"

displayURL="https://github.com/AlaharranHonor/StarWormLightingMod"

logoFile="logo.png"

credits="Silverwolf11420, legenden"

authors="AlaharranHonor"

description='''
SWLM is a function-focused lighting mod. Star Worms spawn below, mash them into Goop with a Mortar and Pestle, spread it over blocks, then place them to make them glow bright! Add these goopy blocks seamlessly into the walls, floor, or ceiling of your style for a well-lit and evenly-lit structure.
'''

[[dependencies.swlm]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.swlm]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.swlm]]
    modId="swdm"
    mandatory=false
    versionRange="[1.18.2,)"
    ordering="AFTER" # Load after to allow addon blocks to be registered first
    side="BOTH"