name: 'Release'

on:
  release:
    types: [published]

jobs:
  build-1-18:
    runs-on: ubuntu-latest
    if: contains(github.event.release.name, '1.18')
    name: 'Release 1.18'
    steps:
      - uses: actions/checkout@v2
        name: "Checkout Repository"
        with:
          ref: "main"
      - name: "Setup JDK 16"
        uses: actions/setup-java@v2
        with: { distribution: "adopt", java-version: "16" }
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle
        id: build
        run: chmod +x gradlew && ./gradlew build curseforge ${{ format('-Pcurseforge_key={0} -Pswe_announcements_hook={1}', secrets.CURSEFORGE_API_KEY, secrets.WEBHOOK_URL) }}
  build1-16:
    runs-on: ubuntu-latest
    if: contains(github.event.release.name, '1.16')
    name: 'Release 1.16'
    steps:
      - uses: actions/checkout@v2
        name: "Checkout Repository"
        with:
          ref: "1.16.5"
      - name: "Setup JDK 16"
        uses: actions/setup-java@v2
        with: { distribution: "adopt", java-version: "8" }
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle
        id: build
        run: chmod +x gradlew && ./gradlew build curseforge ${{ format('-Pcurseforge_key={0} -Pswe_announcements_hook={1}', secrets.CURSEFORGE_API_KEY, secrets.WEBHOOK_URL) }}
